# Generated by Django 4.0.3 on 2022-05-09 12:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbohydrate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calorie', models.DecimalField(decimal_places=2, max_digits=5)),
                ('water', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sugar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fiber', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calcium', models.DecimalField(decimal_places=2, max_digits=5)),
                ('iron', models.DecimalField(decimal_places=2, max_digits=5)),
                ('magnesium', models.DecimalField(decimal_places=2, max_digits=5)),
                ('phosphorus', models.DecimalField(decimal_places=2, max_digits=5)),
                ('potassium', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sodium', models.DecimalField(decimal_places=2, max_digits=5)),
                ('zinc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('copper', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vitamin_a', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vitamin_e', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vitamin_d', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vitamin_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vitamin_b6', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vitamin_b12', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='UserDailyIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2022, 5, 9))),
                ('food_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calorieTracker.fooddata')),
            ],
        ),
    ]
