# Generated by Django 4.0.3 on 2022-06-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdailyintake',
            name='meal',
            field=models.CharField(choices=[('BR', 'Breakfast'), ('LU', 'Lunch'), ('DI', 'Dinner'), ('SN', 'Snacks')], default='BR', max_length=2),
        ),
    ]
