# Generated by Django 4.0.3 on 2022-05-09 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calorieTracker', '0002_alter_fooddata_calcium_alter_fooddata_calorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdailyintake',
            name='user',
            field=models.CharField(default='user', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdailyintake',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
