# Generated by Django 4.0.3 on 2022-05-09 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calorieTracker', '0003_userdailyintake_user_alter_userdailyintake_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdailyintake',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
