# Generated by Django 4.0.3 on 2022-05-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieTracker', '0004_alter_userdailyintake_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdailyintake',
            name='amount',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
