# Generated by Django 4.0.3 on 2022-06-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='owner',
            field=models.CharField(max_length=35),
        ),
    ]
