# Generated by Django 4.0.3 on 2022-04-06 09:12

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('muscles_worked', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('exercise_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_instances', to='workout.exercisedata')),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='owner',
            field=models.CharField(default='vedank', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.AddField(
            model_name='exerciseobject',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workout.workout'),
        ),
    ]
