# Generated by Django 4.0.3 on 2022-04-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_alter_exercisedata_muscles_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisedata',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
